### ISSUE TITLE
Why not put luci interface under Services section?

### ISSUE THREAD

**Issue by snapper2tt** [cokebar/luci-app-vlmcsd#1]
First of all, I'd like to say current release is working great on my LEDE. Just out of curiosity, why not put this luci access under Services section instead of Network, I think it makes more sense from my perspective, and this is only kind of a user recommendation.

**Comment by staritbusfans** [comment]
I have the same idea.

**Comment by cokebar** [comment]
closed via f46281a0b15ea9720f30b372d84770ccdf1e0b59
